### ISSUE TITLE
company info o presenter profile

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#26]
which additional info re company?

**Comment by jprzybylski4** [comment]
company_description
buttons:
- company_website
- profile_facebook
- profile_linkedin
- profile_twitter

ADDITIONAL:
If closer to the event we can separate company details into tabs (otherwise not important at the moment):
- key products (like on EBE) - field product_description
In this case, I'd the profile to look like on EBE if possible - tabs as follows:
- speaker bio
- company details
- key products
- contact

This hasn't been used before but if it's easy to implement (otherwise not important at the moment):
Can we show contact details to the company representative? fname, lname, position, email

**Comment by az** [comment]
5acea6e1085a6c0b3f7ea0e104a5afc29a76282c
